### ISSUE TITLE
Question on use case and architecture

### ISSUE THREAD

**Issue by s2kdrifter** [vitafortis/RaspPiTruckController#1]
What are the use cases that you have in mind?  By that I mean, is the controller supposed to work wirelessly when the vehicle is off?  If so, how do you keep the module on and the BT radio up?  Do you consider the current drain this imposes on the system and if so are steps taken to address?  (e.g. BT LE, etc.)

I think this is a great project and good for you to start this and for sharing the code.  I'll try and contribute as much as I can.

**Comment by vitafortis** [comment]
The use case is pretty simple, I plan on having a powerbank that provides enough power to keep the pi on, but not the screen, so I can use an Android or iOS app to control things remotely. The powerbank will be charged using a USB charger, as my truck does not output any current or anything while the truck is off. It may only provide an additional 10 hours of running time, but typically my truck gets used daily, no more than about 8 to 10 hours without being turned on. If it does lose power, it starts up in about 5 seconds, so by the time the radio is on, the pi kicks back on, and starts charging again. 

I'm wanting to keep it as live as long as possible, without draining the battery, as that defeats the purpose. 

Let me know if you have any other questions or any ideas, always happy to discuss these things.
